YAMLを読み込めるようにした
gcp-kit/fti pull request #11
Opened 2022-01-13 18:16 UTC by mopeneko

Closes #10

2022-01-13 22:33 UTC, 54m reviewed
そういえばgodocない

2022-01-13 22:33 UTC, 54m commented on pkg/inserter/model.go
> +	Version string          `json:"version" yaml:"version"`
goimportやgofmtかかってる？

2022-01-14 01:19 UTC, mopeneko commented
godoc書いた
https://github.com/gcp-kit/fti/pull/11/commits/a7329a7b5ce5f279005eaac496d58c7fd0b24c5e

2022-01-15 15:28 UTC, moezakura commented
@mopeneko :conflict:

2022-01-18 09:40 UTC, chun37 commented on pkg/inserter/model.go
> +type Model struct {
Model って名前は流石にひどいな… って思いました

2022-01-18 11:01 UTC, mopeneko commented on pkg/inserter/model.go
> +type Model struct {
うーん
DataModel?

2022-02-07 11:10 UTC, chun37 commented on pkg/inserter/model.go
> +type Model struct {
Model → Collection
ModelItem → Document
な気がするんよね

2022-02-07 11:27 UTC, mopeneko commented on pkg/inserter/model.go
> +type Model struct {
じゃあ、それで

2022-02-08 07:07 UTC, moezakura reviewed
yamlのサンプル追加をお願いします！

2022-02-08 07:49 UTC, mopeneko commented
@moezakura :done:

2022-02-09 04:06 UTC, moezakura requested changes

2022-02-09 04:06 UTC, moezakura commented on samples/Food/dummies.yaml
> +      origin: Japan
EOFFF

2022-02-17 04:35 UTC, mopeneko commented on samples/Food/dummies.yaml
> +      origin: Japan
Fixed!

2022-02-24 07:18 UTC, moezakura approved these changes
LGTM

2022-02-24 07:18 UTC, merged

2022-02-24 08:57 UTC, chun37 commented
ところで、inserter.go に手が加えられてなくて yaml 読めないのでは？