Feat/sub collection
gcp-kit/fti pull request #6
Opened 2021-12-17 07:18 UTC by chun37

close #2

2021-12-17 08:24 UTC, 54m commented on pkg/inserter/json_inserter.go
> +			errorIndexes := []string{}
makeでお願いします！

2021-12-17 08:24 UTC, 54m commented on pkg/inserter/js_inserter.go
> +			err := j.CreateItem(ctx, fmt.Sprintf("%s/%s/%s", cn, j.ci.refIDs[parentItem.Ref], collectionName), subItems, nowIndexes)
サブコレのサブコレ作りたい時出来なさそう
Top/top_id/Middle/middle_id/Bottom/bottom_id
ってやつできなさそう

2021-12-17 08:24 UTC, 54m commented on pkg/inserter/js_inserter.go
> +			errorIndexes := []string{}
makeでお願いします！

2021-12-17 08:26 UTC, 54m commented on pkg/inserter/js_inserter.go
> +			err := j.CreateItem(ctx, fmt.Sprintf("%s/%s/%s", cn, j.ci.refIDs[parentItem.Ref], collectionName), subItems, nowIndexes)
これは再帰的になっててできるとかだったら見逃してるだけっぽい

2021-12-20 02:43 UTC, moezakura requested changes

2021-12-20 07:42 UTC, chun37 commented on pkg/inserter/js_inserter.go
> +			err := j.CreateItem(ctx, fmt.Sprintf("%s/%s/%s", cn, j.ci.refIDs[parentItem.Ref], collectionName), subItems, nowIndexes)
これは再帰的にやってる
cn が Top だけ
2回目が Top/top_id/Middle
3回目が Top/top_id/Middle/middle_id/Bottom
って感じになる想定

2021-12-20 07:43 UTC, chun37 commented on pkg/inserter/json_model.go
> +	SubCollection map[string][]JsonModelItem `json:"sub_collections"`
最後の最後に「これ複数形だしs付けたほうがよくね？」って雑にs付けて、フィールド名のこと完全にわすれてた

2021-12-22 08:22 UTC, chun37 commented on pkg/inserter/json_inserter.go
> +			errorIndexes := []string{}
fixed https://github.com/gcp-kit/fti/pull/6/commits/1070fd2f3984665045aa6619ebc5be19e23d9d34

2021-12-22 08:22 UTC, chun37 commented on pkg/inserter/js_inserter.go
> +			errorIndexes := []string{}
fixed https://github.com/gcp-kit/fti/pull/6/commits/1070fd2f3984665045aa6619ebc5be19e23d9d34

2021-12-22 08:22 UTC, chun37 commented on pkg/inserter/json_model.go
> +	SubCollection map[string][]JsonModelItem `json:"sub_collections"`
fixed https://github.com/gcp-kit/fti/pull/6/commits/78d59cdf76bffb6cbdc53cd6be7145ebe9e9bfbb

2021-12-22 08:22 UTC, chun37 commented on pkg/inserter/js_inserter.go
> +		if len(parentItem.SubCollection) == 0 {
fixed https://github.com/gcp-kit/fti/pull/6/commits/dca4b3ae3d2c7bf20a0b374ac69368ab8040bb9e

2021-12-23 07:21 UTC, moezakura commented on pkg/inserter/js_inserter.go
> +			err := j.CreateItem(ctx, fmt.Sprintf("%s/%s/%s", cn, j.ci.refIDs[parentItem.Ref], collectionName), subItems, nowIndexes)
分かりづらいのと、今後変更があったりしたときに辛くなるので、 `parentCollection[]` みたいな感じで配列にしてappend下あとにjoin('/')みたいにしてほしいです。

2021-12-23 07:21 UTC, moezakura commented on pkg/inserter/json_inserter.go
> +			err := j.CreateItem(ctx, fmt.Sprintf("%s/%s/%s", cn, j.ci.refIDs[parentItem.Ref], collectionName), subItems, nowIndexes)
js_inserter同様(配列にする件)

2022-01-06 10:35 UTC, chun37 commented on pkg/inserter/json_inserter.go
> +			err := j.CreateItem(ctx, fmt.Sprintf("%s/%s/%s", cn, j.ci.refIDs[parentItem.Ref], collectionName), subItems, nowIndexes)
fmt.Sprintf("%s/%s/%s", cn, j.ci.refIDs[parentItem.Ref], collectionName)
の部分の話？

2022-01-06 11:08 UTC, moezakura commented on pkg/inserter/json_inserter.go
> +			err := j.CreateItem(ctx, fmt.Sprintf("%s/%s/%s", cn, j.ci.refIDs[parentItem.Ref], collectionName), subItems, nowIndexes)
そう

2022-01-12 10:19 UTC, chun37 commented on pkg/inserter/json_inserter.go
> +			err := j.CreateItem(ctx, fmt.Sprintf("%s/%s/%s", cn, j.ci.refIDs[parentItem.Ref], collectionName), subItems, nowIndexes)
fixed https://github.com/gcp-kit/fti/pull/6/commits/dfaaa0885bd51b019ec7e60ca6cadb257a18d873

2022-01-12 10:19 UTC, chun37 commented on pkg/inserter/js_inserter.go
> +			err := j.CreateItem(ctx, fmt.Sprintf("%s/%s/%s", cn, j.ci.refIDs[parentItem.Ref], collectionName), subItems, nowIndexes)
fixed https://github.com/gcp-kit/fti/pull/6/commits/dfaaa0885bd51b019ec7e60ca6cadb257a18d873

2022-01-15 15:29 UTC, moezakura commented
@chun37 :conflict:

2022-01-19 15:43 UTC, moezakura approved these changes
LGTM

2022-01-19 15:43 UTC, merged