docs: README.mdを追加した
gcp-kit/fti pull request #9
Opened 2021-12-22 14:15 UTC by chun37

close #4

2021-12-23 03:04 UTC, 54m commented on README.md
> +1. ビルド `go build cmd/fto/main.go`
```suggestion
1. ビルド `go build cmd/fti/main.go`
```
typo

2021-12-23 07:17 UTC, moezakura requested changes

2021-12-23 07:17 UTC, moezakura commented on README.md
> +謎
firestore_project_on_emulatorはfirestoreのprojectIDですね

2021-12-23 07:17 UTC, moezakura commented on README.md
> +firestore emulator のホスト
空にすると本番環境(実際のFirestore)に接続しに行く趣旨も追加してください。

2022-01-12 09:47 UTC, chun37 commented on README.md
> +謎
projectIDを書くと、どうなるんですか？

2022-01-12 09:48 UTC, chun37 commented on README.md
> +firestore emulator のホスト
本番環境の指定ってどこでやるんですか？

2022-01-12 10:19 UTC, chun37 commented on README.md
> +1. ビルド `go build cmd/fto/main.go`
fixed https://github.com/gcp-kit/fti/pull/9/commits/03d8250236ef1926efdae623e4509ea8eb143926

2022-01-13 12:10 UTC, moezakura commented on README.md
> +謎
当該projectIDにデータが入るようになる

2022-01-13 12:25 UTC, moezakura commented on README.md
> +firestore emulator のホスト
`firestore_emulator_host` を空にすると本番へ接続します。

2022-01-15 15:29 UTC, moezakura commented on README.md
> +firestore emulator のホスト
本番環境のホスト情報は必要なく、空にすると勝手に本番環境にライブラリがつなぐようになります。

2022-01-18 10:00 UTC, chun37 commented on README.md
> +firestore emulator のホスト
naruhodo

2022-01-19 15:43 UTC, moezakura reviewed
configの欄にsubCollectionの説明も入れてほしい

2022-03-04 13:24 UTC, 54m commented on README.md
> +firestore emulator のホスト
勝手に、というより
`gcloud auth application-default login`
とかしてローカルに認証情報が入っていて、かつ
`gcloud config set ProjectID`
してる時に該当のプロジェクトに対して接続される感じ

2022-03-04 13:25 UTC, 54m commented on README.md
> +1. ビルド `go build ./cmd/fti/...`
特定の環境だとこれ上手くいかないから./cmd/fti/*.go の方がいいかも

2022-03-10 06:22 UTC, chun37 commented on README.md
> +firestore emulator のホスト
naruhodo

2022-03-10 06:23 UTC, chun37 commented on README.md
> +1. ビルド `go build ./cmd/fti/...`
おk〜

2022-03-10 06:37 UTC, chun37 commented on README.md
> +firestore emulator のホスト
firestore_emulator_host が空で、firestore_project_on_emulator も空だったらどうなる？
@54m @moezakura

2022-03-10 06:41 UTC, chun37 commented on README.md
> +1. ビルド `go build ./cmd/fti/...`
https://github.com/gcp-kit/fti/pull/9/commits/6660e2a3aaa3780788875027f2774cda31f767fb
fixed

2022-03-10 06:41 UTC, chun37 commented
> configの欄にsubCollectionの説明も入れてほしい
config の欄？

2022-03-10 09:02 UTC, 54m commented on README.md
> +firestore emulator のホスト
firestore_emulator_hostが空だとそもそもGCPに接続しに行く

2022-03-10 09:05 UTC, chun37 commented on README.md
> +firestore emulator のホスト
プロジェクトIDが設定されていなければ、GCPに接続しに行ったとして、何も出来ない気がするけど

2022-03-11 07:25 UTC, moezakura commented
> > configの欄にsubCollectionの説明も入れてほしい
> 
> @moezakura config の欄？

`## 形式` ってところにsubCollectionの書き方も入れてほしいという意

2022-03-11 12:36 UTC, chun37 commented
> `## 形式` ってところにsubCollectionの書き方も入れてほしいという意

json のところに subcollection って書いてある気がするけど、そのほかにも欲しいということ？

2022-05-09 10:59 UTC, moezakura approved these changes
LGTM

2022-05-09 10:59 UTC, merged